- hosts: DNET
  tasks:

    - name: Add Bridge on DNET machine
      command: ovs-vsctl add-br br47
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Set interface
      command: ovs-vsctl add-port br47 vxlan0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Add mode
      command: ip tuntap add mode tap tap0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Up tap0
      command: ifconfig tap0 up
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Add port tap0 in br47
      command: ovs-vsctl add-port br47 tap0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

