- hosts: DNET
  tasks:

    - name: Fetch Github Directory
      command: curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Execute Script
      command: chmod +x openvpn-install.sh
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Automate Script 
      shell: AUTO_INSTALL=y ENDPOINT="172.20.16.245" ./openvpn-install.sh
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Transfer file on cyberlab machine
      fetch:
        src: /home/kawish/client.ovpn
        dest: /home/kawish/vagrant_1/
        flat: yes
      register: out
      become: true
      become_user: root
    - debug: var=out

- hosts: vagrant
  tasks:
    - name: Transfer file on cyberlab machine
      copy:
        src: /home/kawish/vagrant_1/client.ovpn
        dest: /home/cyberlab/centos_1/
      register: out
      become: true
      become_user: root
    - debug: var=out

    - name: Install network manager on cyberlab machine
      command: apt install network-manager-openvpn-gnome openvpn-systemd-resolved
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: Import openvpn file 
      command: nmcli connection import type openvpn file /home/cyberlab/centos_1/client.ovpn
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: UP Connection 
      command: nmcli connection up client
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: Add Bridge on cyberlab machine
      command: ovs-vsctl add-br br7
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: Bridge-Ovs on cyberlab machine
      command: ovs-vsctl add-port br7 wlp8s0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: Close Connection 
      command: ifconfig wlp8s0 0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

    - name: Assign IP
      command: ifconfig br7 172.20.16.246/24
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/centos_1
    - debug: var=out

- hosts: DNET
  tasks:

    - name: Add Bridge on DNET machine
      command: ovs-vsctl add-br br47
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Assign IP
      command: ip tuntap add mode tap tap0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Up tap0
      command: ifconfig tap0 up
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Add port
      command: ovs-vsctl add-port br47 tap0
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Set interface
      command: ovs-vsctl add-port br47 vxlan0 -- set interface vxlan0 type=vxlan option=remote_ip=10.8.0.2
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07
    - debug: var=out

    - name: Transfer file on cyberlab machine
      command: ovs-vsctl add-port br0 vxlan0 -- set interface vxlan0 type=vxlan options=remote_ip=10.8.0.2
      register: out
      become: true
      become_user: root

    - debug: var=out

- hosts: vagrant
  tasks:
    - name: Transfer file on cyberlab machine
      command: ovs-vsctl add-port br0 vxlan0 -- set interface vxlan0 type=vxlan options=remote_ip=10.8.0.1
      register: out
      become: true
      become_user: root
    - debug: var=out