- hosts: vagrant
  tasks:

    - name: Reload Virtual Machine
      command: vagrant reload
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/onethttp
    - debug: var=out

- hosts: DNET
  tasks:

    - name: Reload Virtual Machine
      command: vagrant reload
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/dnethttp
    - debug: var=out