- hosts: vagrant
  tasks:

    - name: Destroy Virtual Machine
      command: vagrant destroy
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/cyberlab/onetmysql
    - debug: var=out


- hosts: DNET
  tasks:
    - name: Destroy Virtual Machine
      command: vagrant destroy
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/dnetmysql
    - debug: var=out