- hosts: vagrant
  vars:
    username:
      cyberlab
  tasks:
    - name: Vagrant up on cyberlab machine
      command: vagrant up
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/{{username}}/onethttp
    - debug: var=out

    - name: Vagrant up on cyberlab machine
      command: vagrant ssh -c "hostname -I | cut -d' ' -f2" 
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/{{username}}/onethttp
    - debug: msg={{out.stdout}}
