- hosts: DNET
  tasks:
    - name: Vagrant up on DNET machine
      command: vagrant up
      register: out
      become: true
      become_user: root
      args:
        chdir: /home/kawish/vagrant_07

    - debug: var=out
